server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/movies"
    schemas: "movies"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12042003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: poster/

base:
  url: "http://localhost:8080"

jwt:
  signerKey: "QpOD7PxEqUCWRB8BU6e+Hv29TQLUuG+0sxxSJZWAPGhrVVszWZU2hT5RhoQTvhgv"
